#include <stdlib.h>
#include <sys/stat.h>
#include <stdbool.h>
#include <stdio.h>
#include <sys/types.h>
#include <string.h>
#include <map>
#include <iostream>
#include <vector>
#include <fstream>
#include <algorithm>
#include "pthread.h"
#include <mpi.h>